language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO_CONFIGURATION=Local
install:
  - pip install -q --use-mirrors -r requirements/local.txt
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
#before_script:
#  - "pep8 --exclude=migrations --ignore=E501,E225 gchiam_cc"
#  - pyflakes -x W gchiam_cc
script:
  - cd gchiam_cc
  - python setup.py test
